name: Documentation

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'src/'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: cd docu && pnpm install
      - run: cd docu && pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docu/src/.vitepress/dist
          cname: docu.xn--rseau-constellation-bzb.ca