name: Tests IPA
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  tests-et-couverture:
    name: On test l'IPA
    runs-on: ubuntu-latest
    steps:
      
      - name: Ouvrir la branche
        uses: actions/checkout@v3

      - name: Installer pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Préparation de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Installer
        run: pnpm install

      - name: Vérifier les tests
        run: pnpm couverture:tous

      - name: Envoyer couverure à Codecov
        uses: codecov/codecov-action@v2
